from django.urls import path
from JobBackend import views

urlpatterns = [
    path('Index', views.Index, name="Index"),
    path('AddCompany', views.AddCompany, name="AddCompany"),
    path('CompanySave', views.CompanySave, name="CompanySave"),
    path('CompanyView', views.CompanyView, name="CompanyView"),
    path('EditCompany', views.EditCompany, name="EditCompany"),
    path('UpdateCompany/<int:dataid>/', views.UpdateCompany, name="UpdateCompany"),
    path('UpdateCompanyButton/<int:dataid>/', views.UpdateCompanyButton, name="UpdateCompanyButton"),
    path('DeleteCompany/<int:dataid>/', views.DeleteCompany, name="DeleteCompany"),
    path('AddJob', views.AddJob, name="AddJob"),
    path('JobSave', views.JobSave, name="JobSave"),
    path('JobView', views.JobView, name="JobView"),
    path('EditJob', views.EditJob, name="EditJob"),
    path('UpdateJob/<int:dataId>/', views.UpdateJob, name="UpdateJob"),
    path('UpdateJobButton/<int:dataId>/', views.UpdateJobButton, name="UpdateJobButton"),
    path('DeleteJob/<int:dataId>/', views.DeleteJob, name="DeleteJob"),
    path('AddCountry', views.AddCountry, name="AddCountry"),
    path('CountrySave', views.CountrySave, name="CountrySave"),
    path('CountryView', views.CountryView, name="CountryView"),
    path('EditCountry', views.EditCountry, name="EditCountry"),
    path('UpdateCountry/<int:dataid>/', views.UpdateCountry, name="UpdateCountry"),
    path('UpdateCountryButton/<int:dataid>/', views.UpdateCountryButton, name="UpdateCountryButton"),
    path('DeleteCountry/<int:dataid>/', views.DeleteCountry, name="DeleteCountry"),
    path('Settings', views.Settings, name="Settings"),
    path('Login', views.Login, name="Login"),
    path('AdminLogin', views.AdminLogin, name="AdminLogin"),
    path('AdminLogout', views.AdminLogout, name="AdminLogout"),
    path('DailyUpdates', views.DailyUpdates, name="DailyUpdates"),
    path('DailyUpdates1', views.DailyUpdates1, name="DailyUpdates1"),
    path('DailyUpdates2', views.DailyUpdates2, name="DailyUpdates2"),
    path('Deleteall/<int:dataid>/', views.Deleteall, name="Deleteall"),
    path('ContactDetails', views.ContactDetails, name="ContactDetails"),
    path('contactdlt/<int:data>/', views.contactdlt, name="contactdlt"),
]