# Generated by Django 3.2.10 on 2024-02-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactusdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAccountDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FrontCompanyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=50, null=True)),
                ('information', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('companyProfile', models.ImageField(blank=True, null=True, upload_to='companyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FrontCountryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('countryFlag', models.ImageField(blank=True, null=True, upload_to='countryFlag')),
            ],
        ),
        migrations.CreateModel(
            name='FrontJobDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('jobDetails', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('contactNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
